baseurl: /kinhnghiemlaptrinh
url: https://ppap-1264589.github.io
theme: jekyll-theme-slate
title: Kinh nghiệm lập trình
permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true
  math_engine: mathjax